project:
  type: website

website:
  title: "Julián Úsuga Ortiz"
  navbar:
    right:
      - cv.qmd
      - real_estate.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



